print("L'Automobile arriva in officina")
print()
print("Piccolo resoconto dei danni")
print()
print("Creazione della lista dei pezzi di ricambio")
print()
a=input("Ho tutti i pezzi in magazzino si/no: ")
if a=="no":
    print()
    print("Trovo i pezzi online")
print()
print("Procedo con la stima del prezzo e dei tempi di riparazione")
print()
print("procedo con avvisare il cliente del prezzo e dei tempi di riparazione")
print()
b=input("Il cliente accetta si/no: ")
if b == "no":
    print()
    print("Il cliente viene a ritirare il veicolo")
    print()
else:
    print()
    print("Prendo i pezzi dal magazzino")
    print()
    c=input("Ho tutti i pezzi in magazzino si/no: ")
    print()
    if c == "no":
        print()
        print("Ordino i pezzi online")
        print()
        print("Mi arrivano i pezzi mancati ordinati")
        print()
    print("Procedo con la riparazione")
    print()
    print("Avviso il cliente che il veicolo è pronto")
    print()
    print("Il cliente viene a ritirare l'auto ed effettua il pagamento")
    
